import Chip from "@material-ui/core/Chip";
import { arrayOf, object } from "prop-types";
import React from "react";
import Badge from 'react-simple-badges'

const Skills = (props) => {
  const { skillsData } = props;

  const getSkills = skillsData.map(function (item, index) {
    return (
      <li key={index}>
        <Chip color="secondary" size="small" label={item.name} />
      </li>
    );
  });

  return (
    <section className="skills">
      <h2 className="text-uppercase">
        <i className="fa fa-lg fa-code"></i> Skills
      </h2>
      <ul className="skills-list">{getSkills}
      <li>
      <Badge name="Adobe Fonts" />
      <Badge name="Adobe Illustrator" />
      <Badge name="Adobe Photoshop" />
      <Badge name="Amazon AWS" />
      <Badge name="Anaconda" />
      <Badge name="Android" />
      <Badge name="Android Studio" />
      <Badge name="Angular" />
      <Badge name="AngularJS" />
      <Badge name="Apache" />
      <Badge name="Apache Ant" />
      <Badge name="Apache Kafka" />
      <Badge name="Apache Solr" />
      <Badge name="Apollo GraphQL" />
      <Badge name="Arduino" />
      <Badge name="Atlassian" />
      <Badge name="Atom" />
      <Badge name="Awesome Lists" />
      <Badge name="Babel" />
      <Badge name="Bitbucket" />
      <Badge name="Bitcoin" />
      <Badge name="Bitly" />
      <Badge name="Blueprint" />
      <Badge name="Bootstrap" />
      <Badge name="Bower" />
      <Badge name="Box" />
      <Badge name="Brave" />
      <Badge name="Buy Me A Coffee" />
      <Badge name="Canonical" />
      <Badge name="Celery" />
      <Badge name="CentOS" />
      <Badge name="Chocolatey" />
      <Badge name="Cisco" />
      <Badge name="Cloudflare" />
      <Badge name="CMake" />
      <Badge name="CodeIgniter" />
      <Badge name="CodePen" />
      <Badge name="CoffeeScript" />
      <Badge name="Composer" />
      <Badge name="Confluence" />
      <Badge name="Couchbase" />
      <Badge name="Coursera" />
      <Badge name="cPanel" />
      <Badge name="Creative Commons" />
      <Badge name="CSS Wizardry" />
      <Badge name="CSS3" />
      <Badge name="Cucumber" />
      <Badge name="curl" />
      <Badge name="D3.js" />
      <Badge name="Datadog" />
      <Badge name="Debian" />
      <Badge name="deepin" />
      <Badge name="DigitalOcean" />
      <Badge name="Discord" />
      <Badge name="Docker" />
      <Badge name="Dropbox" />
      <Badge name="Drupal" />
      <Badge name="DuckDuckGo" />
      <Badge name="Dynamics 365" />
      <Badge name="eBay" />
      <Badge name="Eclipse Vert.x" />
      <Badge name="Electron" />
      <Badge name="ESLint" />
      <Badge name="Ethereum" />
      <Badge name="Evernote" />
      <Badge name="Expo" />
      <Badge name="Express" />
      <Badge name="F-Droid" />
      <Badge name="Facebook" />
      <Badge name="Facebook" />
      <Badge name="Facebook" />
      <Badge name="Facebook" />
      <Badge name="Firebase" />
      <Badge name="Firefox Browser" />
      <Badge name="Flickr" />
      <Badge name="Font Awesome" />
      <Badge name="freedesktop.org" />
      <Badge name="FreeNAS" />
      <Badge name="Genius" />
      <Badge name="Gentoo" />
      <Badge name="Geocaching" />
      <Badge name="GIMP" />
      <Badge name="GIPHY" />
      <Badge name="Git" />
      <Badge name="GitHub" />
      <Badge name="GitHub Actions" />
      <Badge name="GitKraken" />
      <Badge name="GitLab" />
      <Badge name="Gitpod" />
      <Badge name="Glassdoor" />
      <Badge name="Gmail" />
      <Badge name="GNOME" />
      <Badge name="GNU" />
      <Badge name="GNU Bash" />
      <Badge name="Google" />
      <Badge name="Google Ads" />
      <Badge name="Google AdSense" />
      <Badge name="Google Analytics" />
      <Badge name="Google Assistant" />
      <Badge name="Google Calendar" />
      <Badge name="Google Cardboard" />
      <Badge name="Google Cast" />
      <Badge name="Google Chat" />
      <Badge name="Google Chrome" />
      <Badge name="Google Cloud" />
      <Badge name="Google Domains" />
      <Badge name="Google Drive" />
      <Badge name="Google Earth" />
      <Badge name="Google Hangouts" />
      <Badge name="Google Keep" />
      <Badge name="Google Lens" />
      <Badge name="Google Maps" />
      <Badge name="Google Messages" />
      <Badge name="Google My Business" />
      <Badge name="Google Nearby" />
      <Badge name="Google News" />
      <Badge name="Google Photos" />
      <Badge name="Google Search Console" />
      <Badge name="Google Sheets" />
      <Badge name="Google Street View" />
      <Badge name="Google Tag Manager" />
      <Badge name="Google Translate" />
      <Badge name="Gravatar" />
      <Badge name="Grunt" />
      <Badge name="gulp" />
      <Badge name="Hackaday" />
      <Badge name="HackerRank" />
      <Badge name="haveibeenpwned" />
      <Badge name="Helm" />
      <Badge name="Heroku" />
      <Badge name="HipChat" />
      <Badge name="Home Assistant" />
      <Badge name="HTML5" />
      <Badge name="Hulu" />
      <Badge name="Humble Bundle" />
      <Badge name="IBM" />
      <Badge name="IBM Watson" />
      <Badge name="Internet Explorer" />
      <Badge name="IPFS" />
      <Badge name="Jasmine" />
      <Badge name="Java" />
      <Badge name="JavaScript" />
      <Badge name="Jenkins" />
      <Badge name="Jest" />
      <Badge name="Jira" />
      <Badge name="Jira Software" />
      <Badge name="Joomla" />
      <Badge name="JPEG" />
      <Badge name="jQuery" />
      <Badge name="jsDelivr" />
      <Badge name="JSFiddle" />
      <Badge name="JSON" />
      <Badge name="JSON Web Tokens" />
      <Badge name="Kali Linux" />
      <Badge name="KDE" />
      <Badge name="Kubernetes" />
      <Badge name="Laravel" />
      <Badge name="Last.fm" />
      <Badge name="LastPass" />
      <Badge name="Launchpad" />
      <Badge name="Leaflet" />
      <Badge name="Less" />
      <Badge name="LibreOffice" />
      <Badge name="Lighthouse" />
      <Badge name="Linux" />
      <Badge name="Linux Foundation" />
      <Badge name="Linux Mint" />
      <Badge name="Litecoin" />
      <Badge name="Lubuntu" />
      <Badge name="Magento" />
      <Badge name="MailChimp" />
      <Badge name="Manjaro" />
      <Badge name="Mapbox" />
      <Badge name="Markdown" />
      <Badge name="Marketo" />
      <Badge name="Material Design" />
      <Badge name="Material Design Icons" />
      <Badge name="Material-UI" />
      <Badge name="MDN Web Docs" />
      <Badge name="Microsoft" />
      <Badge name="Microsoft Access" />
      <Badge name="Microsoft Edge" />
      <Badge name="Microsoft Excel" />
      <Badge name="Microsoft Office" />
      <Badge name="Microsoft OneDrive" />
      <Badge name="Microsoft OneNote" />
      <Badge name="Microsoft Outlook" />
      <Badge name="Microsoft PowerPoint" />
      <Badge name="Microsoft SQL Server" />
      <Badge name="Microsoft Teams" />
      <Badge name="Microsoft Visio" />
      <Badge name="Microsoft Word" />
      <Badge name="Mocha" />
      <Badge name="Monero" />
      <Badge name="MongoDB" />
      <Badge name="Mozilla" />
      <Badge name="MusicBrainz" />
      <Badge name="MySQL" />
      <Badge name="New Relic" />
      <Badge name="Next.js" />
      <Badge name="NFC" />
      <Badge name="NGINX" />
      <Badge name="ngrok" />
      <Badge name="Node.js" />
      <Badge name="Nodemon" />
      <Badge name="Notepad++" />
      <Badge name="NPM" />
      <Badge name="NuGet" />
      <Badge name="Okta" />
      <Badge name="Open Source Initiative" />
      <Badge name="OpenAPI Initiative" />
      <Badge name="OpenCV" />
      <Badge name="OpenSSL" />
      <Badge name="OpenStreetMap" />
      <Badge name="Oracle" />
      <Badge name="OWASP" />
      <Badge name="p5.js" />
      <Badge name="PagerDuty" />
      <Badge name="Pastebin" />
      <Badge name="PayPal" />
      <Badge name="Phabricator" />
      <Badge name="PHP" />
      <Badge name="PhpStorm" />
      <Badge name="Pi-hole" />
      <Badge name="Plesk" />
      <Badge name="Plex" />
      <Badge name="Podcast Addict" />
      <Badge name="Polymer Project" />
      <Badge name="PostgreSQL" />
      <Badge name="Postman" />
      <Badge name="PowerShell" />
      <Badge name="Prettier" />
      <Badge name="Product Hunt" />
      <Badge name="ProtonMail" />
      <Badge name="Puppet" />
      <Badge name="Python" />
      <Badge name="QEMU" />
      <Badge name="Qubes OS" />
      <Badge name="RabbitMQ" />
      <Badge name="Raspberry Pi" />
      <Badge name="React" />
      <Badge name="React Router" />
      <Badge name="Read the Docs" />
      <Badge name="Red Hat" />
      <Badge name="Red Hat Open Shift" />
      <Badge name="Redis" />
      <Badge name="Redux" />
      <Badge name="Redux-Saga" />
      <Badge name="repl.it" />
      <Badge name="rollup.js" />
      <Badge name="RSS" />
      <Badge name="Salesforce" />
      <Badge name="Sass" />
      <Badge name="Selenium" />
      <Badge name="Semantic UI React" />
      <Badge name="Semantic Web" />

      <Badge name="SemVer" />
      <Badge name="SemVer" />
      <Badge name="Shell" />
      <Badge name="Shopify" />
      <Badge name="Signal" />
      <Badge name="Skype" />
      <Badge name="Skype for Business" />
      <Badge name="Slack" />
      <Badge name="SmartThings" />
      <Badge name="Smashing Magazine" />
      <Badge name="Socket.io" />
      <Badge name="Solidity" />
      <Badge name="SoloLearn" />
      <Badge name="SonarQube" />
      <Badge name="Spring" />
      <Badge name="Stack Exchange" />
      <Badge name="Storybook" />
      <Badge name="Storybook" />
      <Badge name="styled-components" />
      <Badge name="stylelint" />
      <Badge name="Subversion" />
      <Badge name="SVG" />
      <Badge name="Swagger" />
      <Badge name="Tableau" />
      <Badge name="Tails" />
      <Badge name="Tampermonkey" />
      <Badge name="TeamCity" />
      <Badge name="TeamSpeak" />
      <Badge name="TeamViewer" />
      <Badge name="Telegram" />
      <Badge name="TensorFlow" />
      <Badge name="Testing Library" />
      <Badge name="The Register" />
      <Badge name="Three.js" />
      <Badge name="TikTok" />
      <Badge name="TikTok" />
      <Badge name="Tor Browser" />
      <Badge name="Tor Project" />
      <Badge name="Trello" />
      <Badge name="Twilio" />
      <Badge name="Twitter" />
      <Badge name="TypeScript" />
      <Badge name="Ubuntu" />
      <Badge name="Vagrant" />
      <Badge name="VirtualBox" />
      <Badge name="VirusTotal" />
      <Badge name="Visual Studio Code" />
      <Badge name="VLC media player" />
      <Badge name="VMware" />
      <Badge name="Vue.js" />
      <Badge name="W3C" />
      <Badge name="WebAuthn" />
      <Badge name="webcomponents.org" />
      <Badge name="Webmin" />
      <Badge name="Webpack" />
      <Badge name="WebRTC" />
      <Badge name="WebStorm" />
      <Badge name="Wikidata" />
      <Badge name="Wikimedia Commons" />
      <Badge name="Wikipedia" />
      <Badge name="Windows" />
      <Badge name="Wireshark" />
      <Badge name="Wolfram" />
      <Badge name="WordPress" />
      <Badge name="X.Org" />
      <Badge name="XAMPP" />
      <Badge name="XFCE" />
      <Badge name="XMPP" />
      <Badge name="Y Combinator" />
      <Badge name="YouTube" />
      <Badge name="Z-Wave" />
      <Badge name="Zapier" />
      <Badge name="Zelle" />
      <Badge name="Zend Framework" />
      <Badge name="ZeroMQ" />
      <Badge name="Zigbee" />

      <Badge name="Zillow" />
      <Badge name="Zoom" />

      </li>
      </ul>
    </section>
  );
};

Skills.propTypes = {
  skillsData: arrayOf(object).isRequired,
};

export default Skills;
